apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-k0q6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-k0q6
    app.kubernetes.io/part-of: tkrw-pr714-0075-0006-app
  name: devfile-sample-k0q6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-k0q6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-k0q6
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0006-tenant/tkrw-pr714-0075-0006-app/devfile-sample-k0q6@sha256:7b8ced7b0f987d4792f2d8a8a6f8cdf93e559d3345c04950ac3c274413df6b95
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
